### ISSUE TITLE
Not being saved on servers

### ISSUE THREAD

**Issue by LegendNed** [JackFred2/ChestTracker#100]
**Describe the bug**
Any server that uses multiverse plugin or something similar makes it not work (like skyblock)

**To Reproduce**
Going to your island, saving chest, then back to spawn and back to island AND boom nothing is saved

**Expected Result**
For the chest to be saved

**Additional context**
Using - chesttracker-1.19.3-1.1.20

And on top of that why is it so annoying to edit source, due to maven.pkg.github, would love to fix it myself but can seem to even sync/build

**Comment by JackFred2** [comment]
Chest Tracker 1.x is effectively on maintenence right now; this should have some more support in 2.0 when i release it.

Multiverse or Bungeecord plugins make this sort of tricky to work automatically; there's no general way of determining which custom dimension the player is in (as far as I'm aware); they all mainly say "minecraft:overworld", so 1.x thinks it's the same world. This causes issues with an integrity check i have built in, where the Chest Tracker will periodically check memories to see if they're still around, and remove them if not.

I may add certain support for some servers - Hypixel has an API i could use for example - but otherwise you'll be able to manually load/unload memory files in 2.0.
