### ISSUE TITLE
Always forgets the items in chest(sometimes doesn't)

### ISSUE THREAD

**Issue by Netherite2** [JackFred2/ChestTracker#14]
Always forgets the items in chest(sometimes doesn't)

so basically I trained the mod what items were in what chests and everything was working perfectly. Then I left and came back on the server I play and the memory of the mod is just wiped. Also sometimes it didn't happen

It should just store the where are the items data

**Comment by JackFred2** [comment]
Could you upload your latest.log file (the whole thing) when it happens? It should be in your minecraft instance's "logs" directory; If ChestTracker failed to load there should be some error text in there I can use.

**Comment by Netherite2** [comment]
https://drive.google.com/folderview?id=1C9t7eAlCVfn90CZyQfsSrGXg5ZqVRUHJ

**Comment by JackFred2** [comment]
Hi,
I probably wasn't clear enough, apologies - I need the log files of the session when the loading/saving error occured; the one you sent was blank. The correct log file should have the text "Error saving file for " or "No data found for " followed by the world/server name. E.g:
`[main/ERROR]: Error reading file for singleplayer-New World (2)`
`[main/ERROR]: net.minecraft.util.InvalidIdentifierException: Non [a-z0-9/._-] character in path of location: minecraft:test`
or similar.

**Comment by JackFred2** [comment]
Going to mark this as stale as it's been 5 months, feel free to reopen if the issue starts again.

**Comment by Texbio** [comment]
I seem to be having this issue after I restart my client and sometimes when playing.

The first picture is from just opening a few chests and the second one was after i restarted my client.

![1](https://user-images.githubusercontent.com/36513888/178037083-6f97edbc-a72f-4b77-8636-2ecbea73451c.png)
![2](https://user-images.githubusercontent.com/36513888/178037107-1e287b03-4f0a-47dd-a582-d116186ed368.png)

This issue also happens when you leave to do other stuff and when you try to look for a specific item you just cant find it. PLEASE fix this issue. If you need more information please ask me.

fabric-api-0.57.0+1.19
modmenu-4.0.0
cloth-config-7.0.72-fabric
chesttracker-1.19-1.1.17

Minecraft Version: 1.19
Operating System: Mac OS X (x86_64) version 12.4

**Comment by SouthernPixel** [comment]
yea ive also been having this issue but ive also been having an issue with it telling me that something is in a chest/barrel when it isnt actually in it when i check
