### ISSUE TITLE
In-game Crash with Both EasierCrafting & Glowcase Installed

### ISSUE THREAD

**Issue by Samekichi** [JackFred2/ChestTracker#5]
**To Reproduce**
Put any item into a _glowcase:item_display_block_ and then open the inventory page. 

**Crash Report**
https://pastebin.com/3JFGCjfa

**P.S.**
Very sorry for reporting an incorrect reproducing procedure in CurseForge, where this issue should actually be a conflict between 3 mods (and I'm not sure which one could fix it). 
For my debugging, the game runs well when a group of mods are installed, including _Chest Tracker_ and _EasierCrafting_. However, it starts to crash after I add _Glowcase_, which makes me jump to that wrong conclusion without further verification, as at the same time I was having many other issues in my modpack waiting for a check. So sorry again for the previous feedback.

**Comment by JackFred2** [comment]
Hey, don't worry about the feedback thing, it's just easier to keep organised with crash logs on here.  I've managed to recreate the crash - it occurs when you click a block entity that doesn't have a GUI (such as the item display block, or a chest with a block above it), then open your inventory before opening a tracked block since the game start.
